# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/SET165-13U/Documents/GitHub/ENES247/lab9-StopWatch/lab9_3_1/iporfirio_9_3_1/iporfirio_9_3_1.srcs/sources_1/ip/counter_6Bit_dsp48/counter_6Bit_dsp48.xci
# IP: The module: 'counter_6Bit_dsp48' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SET165-13U/Documents/GitHub/ENES247/lab9-StopWatch/lab9_3_1/iporfirio_9_3_1/iporfirio_9_3_1.srcs/sources_1/ip/counter_6Bit_dsp48/counter_6Bit_dsp48_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'counter_6Bit_dsp48'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/SET165-13U/Documents/GitHub/ENES247/lab9-StopWatch/lab9_3_1/iporfirio_9_3_1/iporfirio_9_3_1.srcs/sources_1/ip/counter_6Bit_dsp48/counter_6Bit_dsp48.xci
# IP: The module: 'counter_6Bit_dsp48' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SET165-13U/Documents/GitHub/ENES247/lab9-StopWatch/lab9_3_1/iporfirio_9_3_1/iporfirio_9_3_1.srcs/sources_1/ip/counter_6Bit_dsp48/counter_6Bit_dsp48_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'counter_6Bit_dsp48'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
