# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/SET165-13U/Documents/GitHub/ENES247/lab9-StopWatch/lab9_3_3/iporfirio_9_3_3/iporfirio_9_3_3.srcs/sources_1/ip/CLK_5MHz/CLK_5MHz.xci
# IP: The module: 'CLK_5MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SET165-13U/Documents/GitHub/ENES247/lab9-StopWatch/lab9_3_3/iporfirio_9_3_3/iporfirio_9_3_3.srcs/sources_1/ip/CLK_5MHz/CLK_5MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_5MHz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/SET165-13U/Documents/GitHub/ENES247/lab9-StopWatch/lab9_3_3/iporfirio_9_3_3/iporfirio_9_3_3.srcs/sources_1/ip/CLK_5MHz/CLK_5MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_5MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/SET165-13U/Documents/GitHub/ENES247/lab9-StopWatch/lab9_3_3/iporfirio_9_3_3/iporfirio_9_3_3.srcs/sources_1/ip/CLK_5MHz/CLK_5MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_5MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/SET165-13U/Documents/GitHub/ENES247/lab9-StopWatch/lab9_3_3/iporfirio_9_3_3/iporfirio_9_3_3.srcs/sources_1/ip/CLK_5MHz/CLK_5MHz.xci
# IP: The module: 'CLK_5MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SET165-13U/Documents/GitHub/ENES247/lab9-StopWatch/lab9_3_3/iporfirio_9_3_3/iporfirio_9_3_3.srcs/sources_1/ip/CLK_5MHz/CLK_5MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_5MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/SET165-13U/Documents/GitHub/ENES247/lab9-StopWatch/lab9_3_3/iporfirio_9_3_3/iporfirio_9_3_3.srcs/sources_1/ip/CLK_5MHz/CLK_5MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_5MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/SET165-13U/Documents/GitHub/ENES247/lab9-StopWatch/lab9_3_3/iporfirio_9_3_3/iporfirio_9_3_3.srcs/sources_1/ip/CLK_5MHz/CLK_5MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_5MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
