# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/SET165-13U/Documents/GitHub/ENES247/lab9-StopWatch/lab9_2_3/iporfirio_9_2_3/iporfirio_9_2_3.srcs/sources_1/ip/counter_8Bit_fabric/counter_8Bit_fabric.xci
# IP: The module: 'counter_8Bit_fabric' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SET165-13U/Documents/GitHub/ENES247/lab9-StopWatch/lab9_2_3/iporfirio_9_2_3/iporfirio_9_2_3.srcs/sources_1/ip/counter_8Bit_fabric/counter_8Bit_fabric_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'counter_8Bit_fabric'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/SET165-13U/Documents/GitHub/ENES247/lab9-StopWatch/lab9_2_3/iporfirio_9_2_3/iporfirio_9_2_3.srcs/sources_1/ip/counter_8Bit_fabric/counter_8Bit_fabric.xci
# IP: The module: 'counter_8Bit_fabric' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SET165-13U/Documents/GitHub/ENES247/lab9-StopWatch/lab9_2_3/iporfirio_9_2_3/iporfirio_9_2_3.srcs/sources_1/ip/counter_8Bit_fabric/counter_8Bit_fabric_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'counter_8Bit_fabric'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
